# -*- coding: utf-8 -*-
"""analyser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-os9LWgMsTMriCIzOi1iUGyJJ1RF0u6y
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

import pandas as pd
from pyparsing import StringEnd, oneOf, FollowedBy, Optional, SkipTo

root_data = pd.read_csv('Amal_root.csv', header = None, delimiter = ',')
suffix_data = pd.read_csv('Amal_suffix.csv', header = None, delimiter = ',')


keys = list(root_data[0]) #malayalam_samples
values = list(root_data[1]) #english_samples


suffix_keys = list(suffix_data[0]) #malayalam suffix
suffix_values = list(suffix_data[1]) #english suffix

root_key = list(root_data[0])
root_values = list(root_data[2])


print(keys)
print(values)
print(suffix_keys)
print(suffix_values)
print(root_key)
print(root_values)

dictionary = {keys[i]: values[i] for i in range(len(keys))}
root_dct = {root_key[i]: root_values[i] for i in range(len(root_key))}
suffix_dct = {suffix_keys[i]: suffix_values[i] for i in range(len(suffix_keys))}

inv_suffix_dct = {suffix_values[i]: suffix_keys[i] for i in range(len(suffix_values))}
print(dictionary)
print(root_dct)
print(suffix_dct)
print(inv_suffix_dct)
print("please enter an expression:")
input_val = input()
eng_user_input = dictionary.get(input_val)
print("Transliterate value:",eng_user_input)

endOfString = StringEnd()
suffix = oneOf(suffix_values) + FollowedBy(endOfString)
word = (SkipTo(suffix | endOfString)("root") +
Optional(suffix)("suffix"))
res = word.parseString(eng_user_input)

eng_root =  res[0]
eng_suffix = res[1]

print("Transliterate root:", eng_root )
print("Transliterate suffix:", eng_suffix)

mal_suffix = inv_suffix_dct.get(eng_suffix)



malayalam_root = root_dct.get(input_val)
print("malayalam root:",malayalam_root)
print("malayalam suffix:",mal_suffix)

print("out:",malayalam_root, "+", mal_suffix)

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

import pandas as pd
from pyparsing import StringEnd, oneOf, FollowedBy, Optional, SkipTo

root_data = pd.read_csv('hwords.csv', header = None, delimiter = ',')
suffix_data = pd.read_csv('hsuffix.csv', header = None, delimiter = ',')


keys = list(root_data[0]) #hindi_samples
values = list(root_data[1]) #english_samples


suffix_keys = list(suffix_data[0]) #hindi suffix
suffix_values = list(suffix_data[1]) #english suffix

root_key = list(root_data[0])
root_values = list(root_data[2])


print(keys)
#print(values)
#print(suffix_keys)
#print(suffix_values)
#print(root_key)
#print(root_values)

dictionary = {keys[i]: values[i] for i in range(len(keys))}
root_dct = {root_key[i]: root_values[i] for i in range(len(root_key))}
suffix_dct = {suffix_keys[i]: suffix_values[i] for i in range(len(suffix_keys))}

inv_suffix_dct = {suffix_values[i]: suffix_keys[i] for i in range(len(suffix_values))}

print("please enter an expression:")
input_val = input()
eng_user_input = dictionary.get(input_val)
print("Transliterate value:",eng_user_input)

endOfString = StringEnd()
suffix = oneOf(suffix_values) + FollowedBy(endOfString)
word = (SkipTo(suffix | endOfString)("root") +
Optional(suffix)("suffix"))
res = word.parseString(eng_user_input)

eng_root =  res[0]
eng_suffix = res[1]

print("Transliterate root:", eng_root )
print("Transliterate suffix:", eng_suffix)

hin_suffix = inv_suffix_dct.get(eng_suffix)



hindi_root = root_dct.get(input_val)
print("hindi root:",hindi_root)
print("hindi suffix:",hin_suffix)

print("out:",hindi_root, "+", hin_suffix)